### ISSUE TITLE
Absolute ID (AbID) Feature Support

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/lib_jobs#43]
This is outlined within the PULFALight feature discussion for https://github.com/pulibrary/pulfalight/issues/311. Following discussions with regineheberlein and members of the ArchivesSpace Migration Working Group, a number of requirements were identified:

- Create/Read support for Absolute IDs as resources (ActiveRecord with a REST API for implementation should suffice, at least initially)
- XML serialization for Absolute ID resources
- Synchronization with ArchivesSpace Resources (finding aid EAD XML Documents)
  - Integration with a client for an ArchivesSpace REST client
  - Specifying EAD IDs and linking Absolute IDs to these (within the lib_jobs ActiveRecord Rails model, this is likely just a string attribute for said model)
    - A Rails model attribute will need to store the `repository_id` for the ArchivesSpace EAD
    - A Rails model attribute will need to store the `resource_id` for the ArchivesSpace EAD
  - Requesting and updating the EAD XML elements which should specify the Absolute ID
    - "Give each top container the given container profile"
    - "Give each top container the given location code"

## Outstanding issues for launch
- [x] Codabar algorithm #55 
- [x] Box range support #57 
- [x] Review abID before syncing #58 
- [x] Validate call numbers, report errors #60 
- [ ] Reporting feature #63 
- [x] Production database sync (final step) #59

**Comment by jrgriffiniii** [comment]
Given that colleagues are now working more efficiently with labels on other project repositories and ZenHub boards, I'm going to proceed by following this approach for AbID features on LibJobs. Should this be in error, please freely let me know and this issue can be reopened.
